include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    always_use_package_imports: true
    directives_ordering: true
    constant_identifier_names: false
