name: moform
description: Reactive, model-driven, and type-safe forms for Flutter. A light wrapper around Flutter's TextFormField.
version: 0.1.2
homepage: https://github.com/Tienisto/moform

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
