name: moform
description: Reactive, model-driven, and type-safe forms for Flutter without the overhead of managing a TextEditingController. A light wrapper around Flutter's TextFormField.
version: 0.2.4
repository: https://github.com/Tienisto/moform
topics:
  - forms
  - input
  - reactive
  - model-driven
  - type-safe
funding:
  - https://github.com/sponsors/Tienisto/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.0 <1.0.0'
  meta: ^1.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
