# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION_OLDEST: "3.10.6"
  FLUTTER_VERSION_NEWEST: "3.27.1"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_NEWEST }}
          channel: "stable"

      - name: Dependencies
        run: dart pub get
      - name: Check format
        run: dart format --set-exit-if-changed lib bin test
      - name: Analyze
        run: flutter analyze

  test:
    name: Test (newest Flutter version)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_NEWEST }}
          channel: "stable"

      - name: Dependencies
        run: flutter pub get
      - name: Test
        run: flutter test

  test_legacy:
    name: Test (oldest Flutter version)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_OLDEST }}
          channel: "stable"

      - name: Dependencies
        run: flutter pub get
      - name: Test
        run: flutter test
